### ISSUE TITLE
为啥大佬的网站关闭了新用户注册呢

### ISSUE THREAD

**Issue by df13954** [quibbler01/AndroidTools#1]
想注册，然后评论的，现在无法注册了，QQ也无法登录

**Comment by quibbler01** [comment]
感谢关注[个人网站](http://quibbler.cn/)，因为服务器资源太紧张，支撑不了很多用户。
所以关闭了用户注册，仅作为个人博客使用。
给你新建了用户：ff_frida，密码同修改一下。
